### ISSUE TITLE
Support for iOS

### ISSUE THREAD

**Issue by reinierrr** [minht11/local-music-pwa#13]
I’m very curious about this as I’d like to play music from my Files (iOS) app.

I read the api that is utilized is revolving around Chromium based browsers. I’m experiencing in Safari on my iPhone the “import tracks” button to be unresponsive. 

Am I understanding it right that this only works in Chrome/Edge? 

(I have used [snaeplayer.com/](https://snaeplayer.com/) for the above example)

**Comment by minht11** [comment]
So I am not really sure if previous version worked in iOS before. I recently fixed some Safari specific issues in https://github.com/minht11/local-music-pwa/pull/16. Experience on iOS still looks kinda buggy, but it should at least work now, if you have any issues feel free to report them.

Now full experience only works inside Chromium based browsers. Until Safari and Firefox implement required api they get downgraded experience, since app can't access file references, only their copies, it saves them inside app memory, so for example if you delete file from iOS Files app, the music file copy will still remain inside the player app. But on Chromium browsers the `real` file is used.

**Comment by reinierrr** [comment]
Thanks so much for your reply.

I have tested it just now. First in a private tab which isn’t working (probably of limitations for local storage?), however in a ‘normal’ tab with local files its indeed working like a charm now. I’m really impressed by how the UI and overall experience feel!

In the meantime I had been on the lookout for another solution. I tried to avoid using an app but eventually found an app called Doppi which plays local files and works really well.

I also have a iOS shortcut which loop plays a local file for a X amount of times (based on the input).

I’m going to continue to use and test Snaeplayer, thanks again for your reply and work!
