### ISSUE TITLE
Just some questions

### ISSUE THREAD

**Issue by Nicknaem** [minht11/local-music-pwa#23]
hi, first of all I want to say big thanks to you for making such simple cool music player, its awesome.
I always wanted to make my music player pwa so I got some questions to you

isn't it possible for pwa's to save imported tracks somehow so I don't have to import them every time I open the player?
the only way to bypass importing all music by hand is to choose a fixed folder and import all tracks automatically on startup? it wont be comfortable because it takes time for importing bunch of music.

how do you read music tags? probably with music-metadata package yup? that package says its metadata parser for node.js, how is there node.js involved in pwa? I thought node server was just for dev purposes, does any server run when I launch snaeplayer?

can you edit id3 tags of music? I think would need some other package for that

**Comment by minht11** [comment]
>isn't it possible for pwa's to save imported tracks somehow so I don't have to import them every time I open the player?

After importing tracks once, they should be saved inside browser storage, so even page refresh data is still available. That does sound like a bug. What browser and OS are you using? Maybe one of extensions are interfering?

>how do you read music tags? probably with music-metadata package yup? that package says its metadata parser for node.js, how is there node.js involved in pwa? I thought node server was just for dev purposes, does any server run when I launch snaeplayer?

For parsing metadata we indeed use `music-metadata` package, just because it is written for node doesn't mean it can't run in the browser. There is no server, it's just javascript. However there is a catch some apis like nodeJS buffer needed to be polyfilled for it to work. It all depends on what apis library uses. There is work being done inside `music-metadata` so in the future even that might not be needed https://github.com/minht11/local-music-pwa/blob/349f3352a1e92224cb479e910e7d03773ab5c859/src/helpers/tracks-file-parser/worker/tracks-file-parser-worker.ts#L9-L11

> can you edit id3 tags of music? I think would need some other package for that

As far as I know `music-metadata` doesn't support tag editing by itself so yes some other package would be needed.

**Comment by Nicknaem** [comment]
thanks a lot for response
I tested it on safari ios 15, on windows 10 and on android firefox browser, when I shut down app and reopen it again, imported tracks aren't saved

**Comment by minht11** [comment]
Sorry about that, previous update indeed broke track persistence behaviour. It should be fixed now https://github.com/minht11/local-music-pwa/pull/26

**Comment by Nicknaem** [comment]
![image](https://user-images.githubusercontent.com/55950404/212934685-c5a90b12-b74a-42fe-9aaa-2c4b81bbe088.png)
am I missing something or pwa on safari supports direct access to files?
will it be possible not to duplicate files in indexedDb and use them directly on iphone?

**Comment by minht11** [comment]
Safari and soon Firefox, supports [The File System Access API with Origin Private File System](https://webkit.org/blog/12257/the-file-system-access-api-with-origin-private-file-system/). It does not however support access to native file system, so for now answer is no.
